# 應用程序配置文件
fileStorage:
  file:
    # 文件存儲路徑
    upload-path: C:/uploads
    # 文件上傳大小限制
    max-upload-size: 10MB
    # 文件下載緩存時間（秒）
    download-cache-time: 3600
    # 上傳白名單
    allowed-types:
      - docx
      - jpg
      - pdf
      - png
      - xlsx

cors:
  allowed:
    origins:
      - http://localhost:5173
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    headers:
      - "*"
    exposed-headers: "Content-Disposition"

# logging 配置文件
logging:
  config: classpath:logback-spring.xml
  file:
    path: logs
  level:
        # 根日誌級別
        root: INFO
        # 日誌級別配置
        org.springframework: INFO
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
      total-size-cap: 100MB

# jasypt 配置文件
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${JASYPT_ENCRYPTOR}

# spring 配置文件
spring:
  application:
    name: DocManager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doc_manager
    username: postgres
    password: ENC(mq6AFYn/4jD3hp/6Ie8naA==)
    hikari:
      # HikariCP 連接池名稱
      pool-name: HikariPool-DocManager
      # HikariCP 最大連接池大小
      maximum-pool-size: 50
      # HikariCP 最小空閒連接數
      minimum-idle: 10
      # HikariCP 連接超時時間（毫秒）
      connection-timeout: 500000
      # HikariCP 空閒連接超時時間（毫秒）
      idle-timeout: 60000
      # HikariCP 連接最大存活時間（毫秒）
      max-lifetime: 540000
      # HikariCP 連接測試查詢
      connection-test-query: SELECT 1
      # HikariCP 自動提交
      auto-commit: true
  jackson:
    # 設定時區
    time-zone: GMT+8
    serialization:
      indent-output: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    # 使用 REST API / 前後端分離, 關閉 OpenEntityManagerInView
    open-in-view: false
  output:
    ansi:
      # 啟用 ANSI 顏色輸出
      enabled: always
  servlet:
    multipart:
      # 文件上傳配置
      max-file-size: 20MB
      # 單個請求的最大文件大小
      max-request-size: 50MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

id-generator:
  datacenterId: 1
  machineId: 23
